### ISSUE TITLE
Fetching an access token for service "destination" failed.

### ISSUE THREAD

**Issue by grenik** [SAP/cloud-sdk-js#1563]
Dear colleagues,

When I am doing:
```js
    const destination = await getDestination(destinationName);
    const destinationHeaders = await buildHeadersForDestination(destination);
```
I am getting:
```
... Fetching an access token for service "destination" failed.
ERR     at new ErrorWithCause (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/util/dist/error-with-cause.js:34:16)
ERR     at Object.<anonymous> (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:96:27)
ERR     at step (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:44:23)
ERR     at Object.throw (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:25:53)
ERR     at rejected (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:17:65)
ERR     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR Caused by:
ERR ErrorWithCause: FetchTokenError: Client credentials Grant failed! Cannot read property 'headers' of undefined
ERR     at new ErrorWithCause (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/util/dist/error-with-cause.js:34:16)
ERR     at accessTokenError (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/xsuaa-service.js:294:12)
ERR     at Object.<anonymous> (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/xsuaa-service.js:93:27)
ERR     at step (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/xsuaa-service.js:44:23)
ERR     at Object.throw (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/xsuaa-service.js:25:53)
ERR     at rejected (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/xsuaa-service.js:17:65)
ERR     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR Caused by:
ERR TypeError: Cannot read property 'headers' of undefined
ERR     at mergeDeepProperties (/home/vcap/deps/0/node_modules/axios/lib/core/mergeConfig.js:42:44)
ERR     at Object.forEach (/home/vcap/deps/0/node_modules/axios/lib/utils.js:247:10)
ERR     at mergeConfig (/home/vcap/deps/0/node_modules/axios/lib/core/mergeConfig.js:54:9)
ERR     at Function.request (/home/vcap/deps/0/node_modules/axios-cookiejar-support/lib/index.js:58:57)
ERR     at /home/vcap/deps/0/node_modules/opossum/lib/circuit.js:603:38
ERR     at new Promise (<anonymous>)
ERR     at CircuitBreaker.call (/home/vcap/deps/0/node_modules/opossum/lib/circuit.js:579:12)
ERR     at CircuitBreaker.fire (/home/vcap/deps/0/node_modules/opossum/lib/circuit.js:497:22)
ERR     at post (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/xsuaa-service.js:267:36)
ERR     at Object.<anonymous> (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/xsuaa-service.js:87:42)
```
The issue is reproducible in `1.48.1`
The issue is not reproducible in `1.47.1`

Tried both with on-prem as well as with internet destinations, the auth method is Basic.

Maybe it is somehow relevant to https://github.com/SAP/cloud-sdk-js/issues/1542

**Comment by jjtang1985** [comment]
Hi @grenik ,

Thanks for raising this up.

Unfortunately, I was not able to reproduce it  by running the same code snippets provided.
It would be great, if you can test the version `1.48.0` and share the result to help understand the issue better.

Thank you very much.

Best regards,
Junjie

**Comment by grenik** [comment]
Hi @jjtang1985,

I think I was able to identify the code that introduces the issue, these are two libraries that add cookie support:
```js
const axios = require('axios');

const axiosCookieJarSupport = require('axios-cookiejar-support').default;
const tough = require('tough-cookie');

axiosCookieJarSupport(axios);
axios.defaults.jar = new tough.CookieJar();
axios.defaults.withCredentials = true;
```

I guess these libraries introduce some incompatible changes to the _global_ axios config that is later used by SDK and that SDK doesn’t like. I’ve replaces the first line 
```js
const axios = require('axios');
```

with:
```js
const axios = require('axios').create();
```

So that the cookie support is only introduced to our _local_ axios instance that is _not_ shared with SDK. Now SDK `1.48.1` doesn’t complain anymore.

With `1.48.0` we had the same problem as in #1542 as one of our destinations is on-premise.

Best regards,
Nikolay

**Comment by jjtang1985** [comment]
Hi @grenik ,
Thanks for the example.
I'll test it get back to you soon.

**Comment by jjtang1985** [comment]
Hi @grenik ,

Thank you for the example.
I guess your finding makes sense, as `const axios = require('axios');` will share the same `axios` instance that is used by the SDK. As the default value of `axios.defaults.withCredentials` is `false`, setting it to true might introduce unexpected behaviour.
Fortunately, you found that `axios` provided an API for creating a new instance, which is `require('axios').create();`
I guess the solution you found already solved your issue?

Best regards,
Junjie

**Comment by grenik** [comment]
Hi @jjtang1985,

thanks, the problem is gone.

Best regards,
Nikolay
