### ISSUE TITLE
Generation of a typed OData client (@sap-cloud-sdk/openapi-generator) fails for APIAccountsService

### ISSUE THREAD

**Issue by shardul-sonar-sap** [SAP/cloud-sdk-js#2882]
# Context 
* I am trying to use the BTP API for automating some regular activities that we perform - for example 
  * creation / deletion of sub-accounts
  * creation / deletion of entitlements
  * creation / deletion of instances 
* To do this programmatically I am following the [documentation](https://api.sap.com/api/APIAccountsService/cloud-sdk/JavaScript) which suggests the use of `sap-cloud-sdk` to generate the types for the openapi json / yaml file provided by the [Core Services for SAP BTP.](https://api.sap.com/package/SAPCloudPlatformCoreServices/rest) 

# Steps Followed 
* Downloaded the openapi JSON file for the [Accounts Service](https://api.sap.com/api/APIAccountsService/overview). 
* Installed the generator by running:  `npm install @sap-cloud-sdk/openapi-generator`
* Tried to generate a typed client by running the generator: 
```
npx openapi-generator --input path/to/specification/ --outputDir path/to/client/
```
This command failed with the `error`
```
[2022-09-16T08:48:04.391Z] INFO     (openapi-generator): Finished generation. Don't forget to add @sap-cloud-sdk/openapi to your dependencies.
[2022-09-16T08:48:04.393Z] ERROR    (openapi-generator): Error: Could not generate client. Errors: [
        Error: Could not find placeholder for path parameter(s) 'updateSubaccountGUID'.
]
    at finishAll (/Users/*****/dev/btp-api/node_modules/@sap-cloud-sdk/util/dist/promise.js:22:15)
    at async generateWithParsedOptions (/Users/*****/dev/btp-api/node_modules/@sap-cloud-sdk/openapi-generator/dist/generator.js:58:9)
    at async parseCmdArgs (/Users/*****/dev/btp-api/node_modules/@sap-cloud-sdk/openapi-generator/dist/cli.js:25:13)
```
# Question 
* Is this a bug in the generator or in the JSON file itself? 
My assumption is that it is a bug with the `openapi` file as I tried both `JSON` and `YAML` of the  [Accounts Service](https://api.sap.com/api/APIAccountsService/overview), but still failed with same error, but it worked for the [Entitlements Service](https://api.sap.com/api/APIEntitlementsService/overview). If it is a bug with the JSON file then whom do I ask to get it fixed, because it does not help me regarding what I can do with the error.

**Comment by shardul-sonar-sap** [comment]
Thanks for the quick fix @jjtang1985, 
The workaround seems to work :) 

I have sent the feedback as suggested by you :) Until then I will use the workaround mentioned by you :)
