### ISSUE TITLE
Kyma using Function:  XSUAA URL is not a valid URL: "undefined"

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP/cloud-sdk-js#4287]
function.yaml
```apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: {{ .Values.function.name }}
  namespace: {{ .Values.function.namespace }}
spec:  
  runtime: {{ .Values.function.nodeVersion }}

  env:
    - name: SERVICE_BINDING_ROOT
      value: /bindings

  secretMounts:
    - secretName: cloud-conector-authentication
      mountPath: "/bindings/cloud-conector-authentication"      

    - secretName: connectivity-proxy-binding
      mountPath: "/bindings/connectivity-proxy"      

    - secretName: destination-service-binding
      mountPath: "/bindings/destination-service-instance"
  source: 
    gitRepository:
      reference: {{ .Values.function.branch }}
      baseDir: {{ .Values.function.path }}
      url: {{ .Values.function.gitUrl }}
      auth:
        type: "basic"
        secretName: "git-creds-basic"
  replicas: 1
```
package.json
```{
    "name": "conect-s4",
    "description": "conect S4",
    "version": "1.0.0",
    "devDependencies": {
        "express": "*",
        "js-yaml": "^4.1.0",
        "nodemon": "^3.0.1"
    },
    "scripts": {
        "start": "coffee -o lib/ -c src/waza.coffee",
        "start:dev": "nodemon server.js"
    },
    "main": "server.js",
    "dependencies": {
        "@sap-cloud-sdk/connectivity": "^3.8.0",
        "@sap-cloud-sdk/http-client": "^3.8.0",
        "@sap/xsenv": "^4.1.0",
        "@sap/xssec": "^3.5.0",
        "axios": "^1.6.2",
        "dotenv": "^16.3.1"
    }
}
```
handler.js
```const httpClient = require('@sap-cloud-sdk/http-client');
const xsenv = require('@sap/xsenv');           
const connect = require('@sap-cloud-sdk/connectivity');
const axios = require("axios");

module.exports = {    
    main: async function (event, context) {
        
        const res = event.extensions.response;
        const req = event.extensions.request;
        
        return callSDK(req, res, event );
    }    

}


async function callSDK(req, res, event){
    xsenv.loadEnv()
    //const xsenvLog = xsenv.readServices();
  //  console.log(xsenvLog)
    var xsuaa = xsenv.serviceCredentials({ label: 'xsuaa' });
    console.log("XSUAA: ", xsuaa)

    var connectivity = xsenv.serviceCredentials({ label: 'connectivity' });
  //  console.log(connectivity)
  //  var svc = xsenv.serviceCredentials({ label: 'xsuaa' });
   // console.log(svc)
    const { data } = event;
    try {
        const destinationName  = req.headers['destination-name']
        const jwt = connect.retrieveJwt(req);
        //const parsedUrl = req.url.parse(req.url, true);        
       /* const myCustomParameterEncodingFunction = function (params) {
            const encodedParams = {};
            for (const k in params) {
              encodedParams[k] = encodeURI(params[k].toString());
            }
            console.log(encodedParams) 
            return encodedParams;
        };*/
        const props = { url: req.path, data: req['body'],  method: req.method, headers: { 'X-Requested-With': 'X'}}
        const options = { fetchCsrfToken: false };
        console.log(options, props, destinationName)
        
        const result = await httpClient.executeHttpRequest(
            { destinationName,jwt},
            props,
            options
            
        );
        return res.status(result.status).json(result.data);
    } catch (error) {
        console.log(error)
        return res.status(500).end();
    }
}
```
error
```
47074Z { fetchCsrfToken: false } {
2023-11-17T21:13:07.213670309Z   url: '/sap/opu/odata/<service-s4>/$count',
2023-11-17T21:13:07.213674896Z   data: {},
2023-11-17T21:13:07.213679024Z   method: 'GET',
2023-11-17T21:13:07.213682878Z   headers: { 'X-Requested-With': 'X' }
2023-11-17T21:13:07.213686478Z } S4-DESTINATION
2023-11-17T21:13:09.417808384Z ErrorWithCause: Failed to load destination.
2023-11-17T21:13:09.417832218Z     at /usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-accessor.js:50:15
2023-11-17T21:13:09.417836887Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-17T21:13:09.417840571Z     at async resolveDestination (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-accessor.js:49:33)
2023-11-17T21:13:09.417845163Z     at async /usr/src/app/function/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:69:37
2023-11-17T21:13:09.417849123Z     at async callSDK (/usr/src/app/function/handler.js:46:24)
2023-11-17T21:13:09.417853031Z Caused by:
2023-11-17T21:13:09.417856282Z ErrorWithCause: Failed to add proxy authorization header - client credentials grant failed!
2023-11-17T21:13:09.417860316Z     at proxyAuthorizationHeader (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/connectivity-service.js:87:15)
2023-11-17T21:13:09.417875853Z     ... 14 lines matching cause stack trace ...
2023-11-17T21:13:09.417879096Z     at async getDestination (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-accessor.js:73:10) {
2023-11-17T21:13:09.417881988Z   cause: ErrorWithCause: Failed to add proxy authorization header - client credentials grant failed!
2023-11-17T21:13:09.417884886Z       at proxyAuthorizationHeader (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/connectivity-service.js:87:15)
2023-11-17T21:13:09.417887972Z       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-17T21:13:09.417891086Z       at async proxyHeaders (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/connectivity-service.js:73:29)
2023-11-17T21:13:09.417894091Z       at async addProxyConfigurationOnPrem (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/connectivity-service.js:27:17)
2023-11-17T21:13:09.417897963Z   Caused by:
2023-11-17T21:13:09.417900870Z   Error: XSUAA URL is not a valid URL: "undefined".
2023-11-17T21:13:09.417903889Z       at replaceWithIssuerSubdomain (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/subdomain-replacer.js:14:15)
2023-11-17T21:13:09.417906866Z       ... 8 lines matching cause stack trace ...
2023-11-17T21:13:09.417909701Z       at async getDestination (/usr/src/app/func
tion/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-accessor.js:73:10) {
2023-11-17T21:13:09.417912505Z     cause: Error: XSUAA URL is not a valid URL: "undefined".
2023-11-17T21:13:09.417915624Z         at replaceWithIssuerSubdomain (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/subdomain-replacer.js:14:15)
2023-11-17T21:13:09.417918808Z         at getMultiTenantXsuaaUrl (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/token-accessor.js:65:63)
2023-11-17T21:13:09.417921939Z         at serviceToken (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/token-accessor.js:30:26)
2023-11-17T21:13:09.417925153Z         at proxyAuthorizationHeader (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/connectivity-service.js:83:63)
2023-11-17T21:13:09.417928315Z         at proxyHeaders (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/connectivity-service.js:73:35)
2023-11-17T21:13:09.417931331Z         at addProxyConfigurationOnPrem (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/connectivity-service.js:27:23)
2023-11-17T21:13:09.417936469Z         at DestinationFromServiceRetriever.addProxyConfiguration (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-from-service.js:250:79)
2023-11-17T21:13:09.417940144Z         at DestinationFromServiceRetriever.getDestinationFromDestinationService (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-from-service.js:89:43)
2023-11-17T21:13:09.417943401Z         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-17T21:13:09.417946563Z         at async getDestination (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-accessor.js:73:10)
2023-11-17T21:13:09.417949582Z   }
2023-11-17T21:13:09.417952949Z }
```

XSUAA
```
2023-11-17T21:16:23.155365226Z XSUAA:  {
2023-11-17T21:16:23.155399921Z   clientsecret: '<secutiry>',
2023-11-17T21:16:23.155406099Z   tenantid: '<secutiry>',
2023-11-17T21:16:23.155422494Z   url: 'https://<secutiry>.authentication.br10.hana.ondemand.com',
2023-11-17T21:16:23.155428380Z   tenantmode: 'dedicated',
2023-11-17T21:16:23.155432855Z   verificationkey: 'secutiry>' +
2023-11-17T21:16:23.155487077Z     '-----END PUBLIC KEY-----',
2023-11-17T21:16:23.155491583Z   zoneid: '<secutiry>',
2023-11-17T21:16:23.155496525Z   'credential-type': 'binding-secret',
2023-11-17T21:16:23.155501037Z   identityzone: '<secutiry>',
2023-11-17T21:16:23.155505284Z   identityzoneid: '<secutiry>',
2023-11-17T21:16:23.155509466Z   apiurl: 'https://api.authentication.br10.hana.ondemand.com',
2023-11-17T21:16:23.155513525Z   xsappname: 'cloud-conector-authentication!t1798',
2023-11-17T21:16:23.155517539Z   uaadomain: 'authentication.br10.hana.ondemand.com',
2023-11-17T21:16:23.155521692Z   clientid: 'sb-cloud-conector-authentication!t1798',
2023-11-17T21:16:23.155525534Z   sburl: 'https://internal-xsuaa.authentication.br10.hana.ondemand.com',
2023-11-17T21:16:23.155529728Z   subaccountid: '<secutiry>'
2023-11-17T21:16:23.155533594Z }```

I'm trying to connect to an S4 promise system, using cloud connector. But I couldn't get out of this error.

**Comment by tomfrenken** [comment]
Hey @luizcarlospedrosogomes,

since you are running on Kyma, connectivity works differently than on Cloud Foundry.
When you bind the connectivity service, you also automatically deploy the connectivity proxy to your cluster, which is the component establishing the connection to the cloud connector.
Furthermore, you need to deploy the [transparent proxy](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/transparent-proxy-for-kubernetes), with its [Kyma environment mode](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/transparent-proxy-in-kyma-environment), as well as its CRD [`destination`](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/on-premise-connectivity).
After you've created the destinations, you need to use the SDK's [`registerDestination()`](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#register-destination) and then finally execute the request against these new destinations.
Right now you are setting a bunch of headers and props yourself, this should all be taken care of by the transparent proxy.
Feel free to reach out once you have tried the aforementioned steps / face any isuses.

**Comment by luizcarlospedrosogomes** [comment]
thanks
I will try to follow the steps
but two considerations:
1 - where is this exemplified? Could you give me an example?
2 - isn't the implementation according to the environment the responsibility of this lib? If we have code deployed in Spaces and Kyma will we need different implementations?

**Comment by luizcarlospedrosogomes** [comment]
Step: https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/transparent-proxy-in-kyma-environment
- namespace  sap-transp-proxy-system not exists.

**Comment by tomfrenken** [comment]
Hey @luizcarlospedrosogomes,

> 1 - where is this exemplified? Could you give me an example?

We haven't created a Kyma sample application yet, only for internal test purposes so far, however, it is on our radar that we should create and document a Kyma example in the future.

> 2 - isn't the implementation according to the environment the responsibility of this lib? If we have code deployed in Spaces and Kyma will we need different implementations?

Most of the SDK's functionality is working in both environments, the only exception is on-premise connectivity, where the difference between the two environments would lead to significant resources spent to create an implementation that works exactly the same in both.
As we are currently short on resources and the priority for behavior parity was rather low in the past, you'll have to go with the described approach for now.

**Comment by tomfrenken** [comment]
Regarding your issue with the Transparent Proxy setup, we've also experienced various issues with it in the past, I can only recommend you to directly reach out to them (through JIRA) [here](https://jtrack.wdf.sap.corp/browse/NGPBUG-353263?jql=project%20%3D%20NGPBUG%20AND%20component%20%3D%20%22K8S-Transparent%20Proxy%22), as they are the experts on this component.

**Comment by luizcarlospedrosogomes** [comment]
> Regarding your issue with the Transparent Proxy setup, we've also experienced various issues with it in the past, I can only recommend you to directly reach out to them (through JIRA) [here](https://jtrack.wdf.sap.corp/browse/NGPBUG-353263?jql=project%20%3D%20NGPBUG%20AND%20component%20%3D%20%22K8S-Transparent%20Proxy%22), as they are the experts on this component.

I don't have access to Jira, this seems to be for internal use.

**Comment by luizcarlospedrosogomes** [comment]
https://blogs.sap.com/2023/11/14/it-has-never-been-easier-connecting-cloud-apps-to-internet-and-on-premises-systems-using-sap-btp-connectivity/
Here is an example of use, but there is no CR Destination in the cluster where I am working

**Comment by tomfrenken** [comment]
If the Kyma environment mode I've linked doesn't work properly, you can try to install the helm chart as described in the [lifecycle](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/transparent-proxy-lifecycle-management), this should fix the missing destination CR issue.
