### ISSUE TITLE
TypeError: json.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by aharadkou** [SAP/cloud-sdk-js#4383]
Successfull/Error response from OData service is not parsed properly

TypeError: json.hasOwnProperty is not a function
    at isSelectedProperty (C:\dev\s4-service\node_modules\@sap-cloud-sdk\odata-common\src\entity-base.ts:328:15)
    at C:\dev\s4-service\node_modules\@sap-cloud-sdk\odata-common\src\entity-deserializer.ts:87:42
    at Array.filter (<anonymous>)
    at Object.deserializeEntity (C:\dev\s4-service\node_modules\@sap-cloud-sdk\odata-common\src\entity-deserializer.ts:87:8)
    at C:\dev\s4-service\node_modules\@sap-cloud-sdk\odata-common\src\request-builder\get-by-key-request-builder-base.ts:101:33

Error is caused by this util node_modules\@sap-cloud-sdk\util\dist\object.js
![image](https://github.com/SAP/cloud-sdk-js/assets/57901414/85507871-1daa-4edb-8988-bc84659a4a95)

- node version 18.19.0
- npm version 10.2.3
- SAP Cloud SDK version 3.9.0

**Code Examples**
```
purchaseOrderApi
      .requestBuilder()
      .getByKey(id)
      .execute(this.destination);
```

I've found out that OData request is executed properly but when response is parsed `hasOwnProperty` util fails

**Comment by aharadkou** [comment]
Found out that JSON.parse have been globally overridden by another library I use. This library creates objects with null prototype thats why this code fails
