### ISSUE TITLE
Unable to send email using mail-client

### ISSUE THREAD

**Issue by rpelluru** [SAP/cloud-sdk-js#4472]
Hi Colleagues,
    We are using mail-client npm module to send emails from on-premise mail server using BTP CAP app. Mail server doesn't require any authentication details to send email, but maintained dummy credentials in destination to send email.

Destination:

<img width="1094" alt="image" src="https://github.com/SAP/cloud-sdk-js/assets/140706353/56b9ea60-c52e-471e-907f-02b498df5546">

CAP Code to trigger email:

this.on('sendEmail', async (request) => {
        const mailConfig = {
            to: 'email@mail.com',
            subject: 'BTP Application Test - On Premise Destination',
            text: 'If you receive this e-mail, you are successful.'
          };
          sendMail({ destinationName: 'SMTP' }, [mailConfig]);
    });

I am getting success response in HTTP call, but email is not sent to the user. We are using "@sap-cloud-sdk/mail-client": "^3.11.0" in our project. Could you please guide us to resolve the issue.

Regards,
Rajesh

**Comment by rpelluru** [comment]
Hi @marikaner, when we used NoAuthentication in destination and we got below error

❗️Uncaught Error: The destination 'name: SMTP' does not contain user or password information as properties. The mail-client only supports basic authentication, so \"user\" and \"password\" are required.\n at getCredentials (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/mail-client/dist/mail-client.js:47:15)\n at buildMailDestination (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/mail-client/dist/mail-client.js:24:36)\n at sendMail (/home/vcap/deps/0/node_modules/@sap-cloud-sdk/mail-client/dist/mail-client.js:182:29)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}


Port 25 is the correct one, if I change it to 587. I am getting below error

❗️Uncaught SocksClientError: Socks5 proxy rejected connection - NotAllowed\n at SocksClient.closeSocket (/home/vcap/deps/0/node_modules/socks/build/client/socksclient.js:390:32)\n at SocksClient.handleSocks5FinalHandshakeResponse (/home/vcap/deps/0/node_modules/socks/build/client/socksclient.js:638:18)\n at SocksClient.processData (/home/vcap/deps/0/node_modules/socks/build/client/socksclient.js:334:22)\n at SocksClient.onDataReceivedHandler (/home/vcap/deps/0/node_modules/socks/build/client/socksclient.js:307:14)\n at Socket.onDataReceived (/home/vcap/deps/0/node_modules/socks/build/client/socksclient.js:223:46)\n at Socket.emit (node:events:514:28)\n at addChunk (node:internal/streams/readable:376:12)\n at readableAddChunk (node:internal/streams/readable:349:9)\n at Readable.push (node:internal/streams/readable:286:10)\n at TCP.onStreamRead

I am not getting any error logs if I maintain dummy credentials with client 25 at destination. Will check with Customer and try to get logs from mail server.

**Comment by rpelluru** [comment]
User is getting emails once we updated sendEmail method as below:

sendMail({ destinationName: 'SMTP' }, [mailConfig], {
            tls: {
                rejectUnauthorized: false
              }
          });

Thanks for your help and support
