### ISSUE TITLE
Failed tests on latest main branch

### ISSUE THREAD

**Issue by uroslates** [SAP/cloud-sdk-js#4703]
**Describe the bug**
When running `yarn test` some tests are failing.

```
@sap-cloud-sdk/generator-common:test:  FAIL   generator-common  src/file-writer/copy-file.spec.ts (15.769 s)-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:   ● copyFile › should not overwrite when overwrite is not set
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     expect(received).toBe(expected) // Object.is equality
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     Expected: "old"
@sap-cloud-sdk/generator-common:test:     Received: "new"
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       56 |       encoding: 'utf-8'
@sap-cloud-sdk/generator-common:test:       57 |     });
@sap-cloud-sdk/generator-common:test:     > 58 |     expect(actual).toBe(oldContent);
@sap-cloud-sdk/generator-common:test:          |                    ^
@sap-cloud-sdk/generator-common:test:       59 |   });
@sap-cloud-sdk/generator-common:test:       60 | });
@sap-cloud-sdk/generator-common:test:       61 |
```
```

@sap-cloud-sdk/generator-common:test:  FAIL   generator-common  src/options-per-service.spec.ts (16.212 s)ap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:   ● getOriginalOptionsPerService › returns a config if an existent file path was givenator-common:test: 
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     expect(received).toEqual(expected) // deep equality
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     - Expected  - 6
@sap-cloud-sdk/generator-common:test:     + Received  + 1
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     - Object {
@sap-cloud-sdk/generator-common:test:     -   "some-file": Object {
@sap-cloud-sdk/generator-common:test:     -     "directoryName": "dirName",
@sap-cloud-sdk/generator-common:test:     -     "packageName": "@scope/package-name",
@sap-cloud-sdk/generator-common:test:     -   },
@sap-cloud-sdk/generator-common:test:     - }
@sap-cloud-sdk/generator-common:test:     + Object {}
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       39 |
@sap-cloud-sdk/generator-common:test:       40 |   it('returns a config if an existent file path was given', async () => {
@sap-cloud-sdk/generator-common:test:     > 41 |     expect(await getOriginalOptionsPerService('path/myConfig.json')).toEqual(
@sap-cloud-sdk/generator-common:test:          |                                                                      ^
@sap-cloud-sdk/generator-common:test:       42 |       config
@sap-cloud-sdk/generator-common:test:       43 |     );
@sap-cloud-sdk/generator-common:test:       44 |   });
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       at Object.<anonymous> (src/options-per-service.spec.ts:41:70)
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:   ● getOptionsPerService › builds options per service with existing config file
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     expect(received).resolves.toEqual(expected) // deep equality
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     - Expected  - 2
@sap-cloud-sdk/generator-common:test:     + Received  + 2
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       Object {
@sap-cloud-sdk/generator-common:test:         "path/service": Object {
@sap-cloud-sdk/generator-common:test:     -     "directoryName": "dirName",
@sap-cloud-sdk/generator-common:test:     -     "packageName": "@scope/package-name",
@sap-cloud-sdk/generator-common:test:     +     "directoryName": "service",
@sap-cloud-sdk/generator-common:test:     +     "packageName": "service",
@sap-cloud-sdk/generator-common:test:         },
@sap-cloud-sdk/generator-common:test:       }
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       142 |         optionsPerService: 'path/myConfig.json'
@sap-cloud-sdk/generator-common:test:       143 |       } as any)
@sap-cloud-sdk/generator-common:test:     > 144 |     ).resolves.toEqual({
@sap-cloud-sdk/generator-common:test:           |                ^
@sap-cloud-sdk/generator-common:test:       145 |       'path/service': {
@sap-cloud-sdk/generator-common:test:       146 |         directoryName: 'dirName',
@sap-cloud-sdk/generator-common:test:       147 |         packageName: '@scope/package-name'
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       at Object.toEqual (../../node_modules/expect/build/index.js:174:22)
@sap-cloud-sdk/generator-common:test:       at Object.<anonymous> (src/options-per-service.spec.ts:144:16)
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:   ● getOptionsPerService › builds options per service with partial options per service.
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     expect(received).resolves.toEqual(expected) // deep equality
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:     - Expected  - 2
@sap-cloud-sdk/generator-common:test:     + Received  + 1
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       Object {
@sap-cloud-sdk/generator-common:test:         "path/service": Object {
@sap-cloud-sdk/generator-common:test:           "directoryName": "service",
@sap-cloud-sdk/generator-common:test:     -     "packageName": "@scope/package-name",
@sap-cloud-sdk/generator-common:test:     -     "serviceName": "Readable Name",
@sap-cloud-sdk/generator-common:test:     +     "packageName": "service",
@sap-cloud-sdk/generator-common:test:         },
@sap-cloud-sdk/generator-common:test:       }
@sap-cloud-sdk/generator-common:test: 
@sap-cloud-sdk/generator-common:test:       168 |         optionsPerService: 'path/myPartialConfig.json'
@sap-cloud-sdk/generator-common:test:       169 |       } as any)
@sap-cloud-sdk/generator-common:test:     > 170 |     ).resolves.toEqual({
@sap-cloud-sdk/generator-common:test:           |                ^
@sap-cloud-sdk/generator-common:test:       171 |       'path/service': {
@sap-cloud-sdk/generator-common:test:       172 |         directoryName: 'service',
@sap-cloud-sdk/generator-common:test:       173 |         packageName: '@scope/package-name',
```
```

ssap-cloud-sdk/connectivit FAIL   util  src/logger/cloud-sdk-logger.spec.ts (27.956 s)
@sap-cloud-sdk/util:test:   ● Cloud SDK Logger › set global transport › should replace all transports in all active loggers with the global transport
@sap-cloud-sdk/util:test: 
@sap-cloud-sdk/util:test:     ENOENT: no such file or directory, stat '/Users/I563210/workspaces/code-generators/SAP/cloud-sdk-js/node_modules/.depcheck-WPj8C3dG/node_modules/.bin/sass'
@sap-cloud-sdk/util:test: 
@sap-cloud-sdk/util:test:       279 |       mock({
@sap-cloud-sdk/util:test:       280 |         'test.log': 'content',
@sap-cloud-sdk/util:test:     > 281 |         [rootNodeModules]: mock.load(rootNodeModules)
@sap-cloud-sdk/util:test:           |                                 ^
@sap-cloud-sdk/util:test:       282 |       });
@sap-cloud-sdk/util:test:       283 |       const fileTransport = new transports.File({
@sap-cloud-sdk/util:test:       284 |         filename: 'test.log',
@sap-cloud-sdk/util:test: 
@sap-cloud-sdk/util:test:       at Object.<anonymous> (../../node_modules/mock-fs/lib/index.js:41:29)
@sap-cloud-sdk/util:test:       at ../../node_modules/mock-fs/lib/loader.js:86:22
@sap-cloud-sdk/util:test:           at Array.forEach (<anonymous>)
@sap-cloud-sdk/util:test:       at addDir (../../node_modules/mock-fs/lib/loader.js:84:26)
@sap-cloud-sdk/util:test:       at ../../node_modules/mock-fs/lib/loader.js:93:7
@sap-cloud-sdk/util:test:           at Array.forEach (<anonymous>)
@sap-cloud-sdk/util:test:       at addDir (../../node_modules/mock-fs/lib/loader.js:84:26)
@sap-cloud-sdk/util:test:       at ../../node_modules/mock-fs/lib/loader.js:93:7
@sap-cloud-sdk/util:test:           at Array.forEach (<anonymous>)
@sap-cloud-sdk/util:test:       at addDir (../../node_modules/mock-fs/lib/loader.js:84:26)
@sap-cloud-sdk/util:test:       at ../../node_modules/mock-fs/lib/loader.js:93:7
@sap-cloud-sdk/util:test:           at Array.forEach (<anonymous>)
@sap-cloud-sdk/util:test:       at addDir (../../node_modules/mock-fs/lib/loader.js:84:26)
@sap-cloud-sdk/util:test:       at ../../node_modules/mock-fs/lib/loader.js:116:14
@sap-cloud-sdk/util:test:       at bypass (../../node_modules/mock-fs/lib/bypass.js:23:14)

```

**To Reproduce**

1. Do a fresh project pull (main branch)
2. Install deps using yarn
3. Run all the test by running `yarn test`
4. Find errors by searching for Error or FAIL.

**Expected behavior**
That all exsiting tests are succeeding.

**Screenshots**
None.

**Used Versions:**

- node version via `node -v` v20.12.2
- npm version via `npm -v` 10.5.0
- SAP Cloud SDK version you used as dependency  Latest commit https://github.com/SAP/cloud-sdk-js/commit/022adaebaa8ac5ac0d6b4676eb0980c03b5ee001

**Comment by tomfrenken** [comment]
Hi @uroslates, thanks for raising the issue.
If you run `yarn test` in any specific module, this problem should disappear.
Due to how we mock the file system, running all tests of all modules in parallel can cause issues.
