### ISSUE TITLE
SAP Lib-> @sap-cloud-sdk/core

### ISSUE THREAD

**Issue by zarar1210** [SAP/cloud-sdk-js#4955]
Hi 

I'm using this code for API request, 

"use strict";
const httpclient = require('@sap-cloud-sdk/core');
const handleErrorResponse = require('./errorHandler');

```
async function callPostApi(req, destination, res) {
    await httpclient.executeHttpRequest(
        {
            destinationName: destination,
        },
        {
            method: 'POST',
            url: req.url,
            data: req.body,
            maxContentLength: Infinity,
            maxBodyLength: Infinity,
            headers: {
                "Content-Type": "application/json"
            },
        }
    ).then(response => {
        res.status(200).send(response.data);
    }).catch(error => {
        handleErrorResponse(req, res, error);
    });
}

module.exports = {
    callPostApi
};
```

But getting this error, Failed to Load Destination" when consuming external service

 ```
error:         ErrorWithCause: Failed to load destination.
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT     at new ErrorWithCause (/home/vcap/app/node_modules/@sap-cloud-sdk/core/node_modules/@sap-cloud-sdk/util/dist/error-with-cause.js:34:16)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT     at /home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/http-client/http-client.js:222:15
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT Caused by:
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT Error: No binding to an XSUAA service instance found. Please make sure to bind an instance of the XSUAA service to your application.
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT     at selectXsuaaInstance (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/environment-accessor.js:250:15)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT     ... 5 lines matching cause stack trace ...
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT   cause: Error: No binding to an XSUAA service instance found. Please make sure to bind an instance of the XSUAA service to your application.
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT       at selectXsuaaInstance (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/environment-accessor.js:250:15)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT       at getXsuaaServiceCredentials (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/environment-accessor.js:210:11)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT       at Function.<anonymous> (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/destination/destination-from-service.js:121:98)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT       at step (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/destination/destination-from-service.js:44:23)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT       at Object.next (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/destination/destination-from-service.js:25:53)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT       at fulfilled (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/destination/destination-from-service.js:16:58)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2024-09-01T23:14:17.38+0530 [APP/PROC/WEB/2] OUT }
```

**Comment by tomfrenken** [comment]
Hi @zarar1210  we do not support the core package, other than that please read the logs instead of opening an issue.
